apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: jenkins
 namespace: argocd
spec:
 project: default
 source:
   repoURL: 'https://charts.jenkins.io'
   chart: 'jenkins'
   targetRevision: 5.6.3  # Specify the chart version you want to use
   helm:
    parameters:
      - name: controller.admin.password
        value: "admin123"  # Set your admin password
    # valueFiles:
    #       - argocd_jenkins_values.yaml


 # Here we will have a properties for overriding the jenkins setup
 destination:
   server: 'https://kubernetes.default.svc'
   namespace: jenkins
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - CreateNamespace=true
